services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - node-a
    networks:
      - app-network

  node-a:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - node-b
    networks:
      - app-network

  node-b:
    build:
      context: ./backend
      dockerfile: Dockerfile.nodeb
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge